### ISSUE TITLE
Make rules configurable

### ISSUE THREAD

**Issue by dorzey** [autotraderuk/oliver-twist#10]
Read rule configuration from a single config yml file
```
global:
    - id: <rule_name_1>
      enabled: false
    - id: <rule_name_2>
      enabled: false
```

All rules will be enabled be default.
