### ISSUE TITLE
Add dag test configuration

### ISSUE THREAD

**Issue by dorzey** [autotraderuk/oliver-twist#2]
[See](https://getdbt.slack.com/archives/C0VLNUUTZ/p1608216163392300?thread_ts=1608206852.387600&cid=C0VLNUUTZ)

**Comment by christineberger** [comment]
What I was thinking for this (and this might be at the dbt_project.yml level?) that there could be a configuration (and to be honest, not sure if this is possible without modifying core dbt):

```yaml
manifest:
   tests:
      - rejoins
         severity: warning
      - no_source_injection
         severity: failure
```

So for example, we would just get a warning if our models take part in a rejoin. We would get a failure (like what we see when running `dbt test`) if our model flow doesn't lead back to a source.
